export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_FAILED = 'UPDATE_APPOINTMENT_FAILED';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST';
export const DELETE_APPOINTMENT_FAILED = 'DELETE_APPOINTMENT_FAILED';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENTSUCCESST';
export const COPY_APPOINTMENT_ID = 'COPY_APPOINTMENT_ID';
export const DUPLICATE_APPOINTMENT_REQUEST = 'DUPLICATE_APPOINTMEN_REQUEST';
export const DUPLICATE_APPOINTMENT_FAILED = 'DUPLICATE_APPOINTMEN__FAILED';
export const DUPLICATE_APPOINTMENT_SUCCESS = 'DUPLICATE_APPOINTMEN_SUCCESS';
export const OPEN_REPORT_MODAL = 'OPEN_REPORT_MODAL';
export const REPORT_APPOINTMENT_SUCCESS = 'REPORT_APPOINTMEN_SUCCESS';
export const REPORT_APPOINTMENT_FAILED = 'REPORT_APPOINTMEN__FAILED';
export const REPORT_APPOINTMENT_REQUEST = 'REPORT_APPOINTMEN_REQUEST';
export const GET_DISPO_REQUEST = 'GET_DISPO_REQUEST';
export const GET_DISPO_SUCCESS = 'GET_DISPO_SUCCESS';
export const GET_DISPO_FAILED = 'GET_DISPO_FAILED';

export const CREATE_RDV_REQUEST = 'CREATE_RDV_REQUEST'
export const CREATE_RDV_REQUEST_SUCCESS = 'CREATE_RDV_REQUEST_SUCCESS'
export const CREATE_RDV_REQUEST_FAILED = 'CREATE_RDV_REQUEST_FAILED'

export const CLEAR_ALL_ERR_MSG_PR = 'CLEAR_ALL_ERR_MSG_PR';

