export const RESET_APP = 'RESET_APP';
export const AUTHER = 'AUTHER';
export const AGENDA_DATE_CLICK = 'AGENDA_DATE_CLICK';
export const SHOW_CALENDAR_LOADER = 'SHOW_CALENDAR_LOADER';
export const EVENT_CLICK = 'EVENT_CLICK';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SHOW_MODAL_DEL_RESSOURCE = 'SHOW_MODAL_DEL_RESSOURCE';

export const GET_STRUCTURE_INFO = 'GET_STRUCTURE_INFO';
export const GET_STRUCTURE_INFO_SUCCESS = 'GET_STRUCTURE_INFO_SUCCESS';
export const GET_STRUCTURE_INFO_FAILED = 'GET_STRUCTURE_INFO_FAILED';

export const TOGGLE_PRATICIEN_PANEL = "TOGGLE_PRATICIEN_PANEL"
export const VERIFY_TOKEN = "VERIFY_TOKEN"
export const ISTOKENVALID = "IsTokenValid"
export const DISCONNECT_USER = "DISCONNECT_USER"