export const GET_ALL_LIEUX = 'GET_ALL_LIEUX';
export const GET_ALL_LIEUX_SUCCESS = 'GET_ALL_LIEUX_SUCCESS';

export const POST_LIEU_REQUEST = 'POST_LIEU_REQUEST';
export const POST_LIEU_REQUEST_SUCCESS = 'POST_LIEU_REQUEST_SUCCESS';
export const POST_LIEU_REQUEST_FAILED = 'POST_LIEU_REQUEST_FAILED';

export const UPDATE_LIEU_REQUEST = 'UPDATE_LIEU_REQUEST';
export const UPDATE_LIEU_REQUEST_SUCCESS = 'UPDATE_LIEU_REQUEST_SUCCESS';
export const UPDATE_LIEU_REQUEST_FAILED = 'UPDATE_LIEU_REQUEST_FAILED';

export const DELETE_LIEU_REQUEST = 'DELETE_LIEU_REQUEST';
export const DELETE_LIEU_REQUEST_SUCCESS = 'DELETE_LIEU_REQUEST_SUCCESS';
export const DELETE_LIEU_REQUEST_FAILED = 'DELETE_LIEU_REQUEST_FAILED';
