export const GET_ALL_MOTIFS = 'GET_ALL_MOTIFS';
export const GET_ALL_MOTIFS_SUCCESS = 'GET_ALL_MOTIFS_SUCCESS';
export const GET_ALL_MOTIFS_FAILED = 'GET_ALL_MOTIFS_FAILED';

export const POST_MOTIF_REQUEST = 'POST_MOTIF_REQUEST';
export const POST_MOTIF_REQUEST_SUCCESS = 'POST_MOTIF_REQUEST_SUCCESS';
export const POST_MOTIF_REQUEST_FAILED = 'POST_MOTIF_REQUEST_FAILED';

export const UPDATING_MOTIF_REQUEST = 'UPDATING_MOTIF_REQUEST';
export const UPDATING_MOTIF_REQUEST_SUCCESS = 'UPDATING_MOTIF_REQUEST_SUCCESS';
export const UPDATING_MOTIF_REQUEST_FAILED = 'UPDATING_MOTIF_REQUEST_FAILED';

export const DELETE_MOTIF_REQUEST = 'DELETE_MOTIF_REQUEST';
export const DELETE_MOTIF_REQUEST_SUCCESS = 'DELETE_MOTIF_REQUEST_SUCCESS';
export const DELETE_MOTIF_REQUEST_FAILED = 'DELETE_MOTIF_REQUEST_FAILED';

export const GET_MOTIFS_BY_SPECS = "GET_MOTIFS_BY_SPECS";
export const GET_MOTIFS_BY_SPECS_SUCCESS = "GET_MOTIFS_BY_SPECS_SUCCESS";
export const SEARCH_MOTIF_REQUEST = 'SEARCH_MOTIF_REQUEST';
export const SEARCH_MOTIF_SUCCESS = 'SEARCH_MOTIF_SUCCESS';
export const SEARCH_MOTIF_FAILLED = 'SEARCH_MOTIF_FAILLED';

// search without backend
export const SEARCH_WB_MOTIF= 'SEARCH_WB_MOTIF';

export const CLEAR_ALL_ERR_MSG_MOTIFS = 'CLEAR_ALL_ERR_MSG_MOTIFS';

