export const GET_ALL_SPECIALITIES = 'GET_ALL_SPECIALITIES';
export const GET_ALL_SPECIALITIES_SUCCESS = 'GET_ALL_SPECIALITIES_SUCCESS';

export const POST_SPEC_REQUEST = 'POST_SPEC_REQUEST';
export const POST_SPEC_REQUEST_SUCCESS = 'POST_SPEC_REQUEST_SUCCESS';
export const POST_SPEC_REQUEST_FAILED = 'POST_SPEC_REQUEST_FAILED';

export const UPDATE_SPECIALITY_REQUEST = 'UPDATE_SPECIALITY_REQUEST';
export const UPDATE_SPECIALITY_REQUEST_SUCCESS =
  'UPDATE_SPECIALITY_REQUEST_SUCCESS';
export const UPDATE_SPECIALITY_REQUEST_FAILED =
  'UPDATE_SPECIALITY_REQUEST_FAILED';

export const DELETE_SPEC_REQUEST = 'DELETE_SPEC_REQUEST';
export const DELETE_SPEC_REQUEST_SUCCESS = 'DELETE_SPEC_REQUEST_SUCCESS';
export const DELETE_SPEC_REQUEST_FAILED = 'DELETE_SPEC_REQUEST_FAILED';

export const SEARCH_SPECIALITY_REQUEST = 'SEARCH_SPECIALITY_REQUEST';
export const SEARCH_SPECIALITY_SUCCESS = 'SEARCH_SPECIALITY_SUCCESS';
export const SEARCH_SPECIALITY_FAILLED = 'SEARCH_SPECIALITY_FAILLED';
