export const GET_ALL_CONSIGNES = "GET_ALL_CONSIGNES"
export const GET_ALL_CONSIGNES_SUCCESS = "GET_ALL_CONSIGNES_SUCCESS"
export const GET_ALL_CONSIGNES_FAILED = "GET_ALL_CONSIGNES_FAILED"

export const UPDATE_CONSIGNE = "UPDATE_CONSIGNE"
export const UPDATE_CONSIGNE_SUCCESS = "UPDATE_CONSIGNE_SUCCESS"
export const UPDATE_CONSIGNE_FAILED = "UPDATE_CONSIGNE_FAILED"

export const DELETE_CONSIGNE = "DELETE_CONSIGNE"
export const DELETE_CONSIGNE_FAILED = "DELETE_CONSIGNE_FAILED"
export const DELETE_CONSIGNE_SUCCESS = "DELETE_CONSIGNE_SUCCESS"

export const CREATE_CONSIGNE = "CREATE_CONSIGNE"
export const CREATE_CONSIGNE_SUCCESS = "CREATE_CONSIGNE_SUCCESS"
export const CREATE_CONSIGNE_FAILED = "CREATE_CONSIGNE_FAILED"

export const SEARCH_CONSIGNE_REQUEST = "SEARCH_CONSIGNE_REQUEST"
export const SEARCH_CONSIGNE_SUCCESS = "SEARCH_CONSIGNE_SUCCESS"
export const SEARCH_CONSIGNE_FAILLED = "SEARCH_CONSIGNE_FAILLED"
