export const GET_PRATICIENS_REQUEST = 'GET_PRATICIENS_REQUEST';
export const GET_PRATICIENS_SUCCESS = 'GET_PRATICIENS_SUCCESS';
export const GET_PRATICIENS_FAILED = 'GET_PRATICIENS_FAILED';

export const GET_ALL_PRATICIENS_REQUEST = 'GET_ALL_PRATICIENS_REQUEST';
export const GET_ALL_PRATICIENS_SUCCESS = 'GET_ALL_PRATICIENS_SUCCESS';
export const GET_ALL_PRATICIENS_FAILED = 'GET_ALL_PRATICIENS_FAILED';
export const SAVE_CHECKED_PRACTITIONERS = 'SAVE_CHECKED_PRACTITIONERS';

export const POST_PRATICIEN_REQUEST = 'POST_PRATICIEN_REQUEST';
export const POST_PRATICIEN_REQUEST_SUCCESS = 'POST_PRATICIEN_REQUEST_SUCCESS';
export const POST_PRATICIEN_REQUEST_FAILED = 'POST_PRATICIEN_REQUEST_FAILED';

export const UPDATE_PRATICIEN_REQUEST = 'UPDATE_PRATICIEN_REQUEST';
export const UPDATE_PRATICIEN_REQUEST_SUCCESS =
  'UPDATE_PRATICIEN_REQUEST_SUCCESS';
export const UPDATE_PRATICIEN_REQUEST_FAILED =
  'UPDATE_PRATICIEN_REQUEST_FAILED';

export const DELETE_PRATICIEN_REQUEST = 'DELETE_PRATICIEN_REQUEST';
export const DELETE_PRATICIEN_REQUEST_SUCCESS =
  'DELETE_PRATICIEN_REQUEST_SUCCESS';
export const DELETE_PRATICIEN_REQUEST_FAILED =
  'DELETE_PRATICIEN_REQUEST_FAILED';
