export const GET_ALL_PATIENT = 'GET_ALL_PATIENT';
export const GET_ALL_PATIENT_SUCCESS = 'GET_ALL_PATIENT_SUCCESS';
export const GET_ALL_PATIENT_FAILED = 'GET_ALL_PATIENT_FAILED';

export const POST_PATIENT_REQUEST = 'POST_PATIENT_REQUEST';
export const POST_PATIENT_REQUEST_SUCCESS = 'POST_PATIENT_REQUEST_SUCCESS';
export const POST_PATIENT_REQUEST_FAILED = 'POST_PATIENT_REQUEST_FAILED';

export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST';
export const UPDATE_PATIENT_REQUEST_SUCCESS = 'UPDATE_PATIENT_REQUEST_SUCCESS';
export const UPDATE_PATIENT_REQUEST_FAILED = 'UPDATE_PATIENT_REQUEST_FAILED';

export const DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST';
export const DELETE_PATIENT_REQUEST_SUCCESS = 'DELETE_PATIENT_REQUEST_SUCCESS';
export const DELETE_PATIENT_REQUEST_FAILED = 'DELETE_PATIENT_REQUEST_FAILED';
