export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
export const RESET_ALL_FIELD = 'RESET_ALL_FIELD';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_REQUEST_SUCCESS = 'POST_USER_REQUEST_SUCCESS';
export const POST_USER_REQUEST_FAILED = 'POST_USER_REQUEST_FAILED';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';
export const UPDATE_USER_REQUEST_FAILED = 'UPDATE_USER_REQUEST_FAILED';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_REQUEST_FAILED = 'DELETE_USER_REQUEST_FAILED';

export const FILTERING_ON_USERS = 'FILTERING_ON_USERS';
export const UNFILTERED_ON_USERS = 'UNFILTERED_ON_USERS';

export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILLED = 'SEARCH_USER_FAILLED';
export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
